name: "Install clang-tidy plugin"
description: "Build and install clang-tidy plugin to the host runner"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          llvm-18-dev clang-18 libclang-18-dev \
          cmake make g++ git

    - name: Build clang-tidy plugin
      shell: bash
      run: |
        cd "$GITHUB_ACTION_PATH/clang-tidy-std-prefix"
        cmake -B build
        cmake --build build

    - name: Install plugin to host
      shell: bash
      run: |
        sudo cp \
          "$GITHUB_ACTION_PATH/clang-tidy-std-prefix/build/libclangTidyStdPrefixPlugin.so" \
          /usr/local/lib/
